# base image
FROM node:12.3.0

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /analytics8

# add `/app/node_modules/.bin` to $PATH
ENV PATH /analytics8/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /analytics8/package.json
RUN npm install
RUN npm install -g @angular/cli@8.3.20

# add app
COPY . /analytics8

# start app
CMD ng serve --prod --host 0.0.0.0 --port 4200 --public-host 35.193.245.80
